### ISSUE TITLE
Payment Confirmation after Delivery

### ISSUE THREAD

**Issue by KingOlami** [ashishnitinpatil/django-oscar-cash-on-delivery#1]
There is no means of confirming payment after delivery has been made

**Comment by ashishnitinpatil** [comment]
Hi, as discussed, there's currently no functionality to do that. But it should not be very hard to implement. You only need to record a payment event like "received" or "collected", and add corresponding dashboard form. We are not actually using Cash on delivery method in our current project, so didn't feel the need to add that. Please feel free to submit a PR with your implementation.

**Comment by KingOlami** [comment]
hi kindly help look into it

**Comment by ashishnitinpatil** [comment]
For adding new dashboard views with forms, take a look at the existing oscar views that do it, particularly  [OrderDetailView](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/dashboard/orders/views.py#L430). You can reuse the add_payment_event from it, inside your very own view inside dashboard/cashondelivery/views.py

**Comment by KingOlami** [comment]
tried it but messed everything up
had to use git to restore previous version. If you could take a moment to show codes that would be greatly appreciated

**Comment by ashishnitinpatil** [comment]
Fixed in https://github.com/ashishnitinpatil/django-oscar-cash-on-delivery/commit/7b8d23a3b0a977b37d2d8bf42979a1255345bde5
If transaction is not confirmed, it will show an action button, which basically posts to the same view to get the transaction confirmed.

**Comment by SalahAdDin** [comment]
@ashishnitinpatil thank you.

**Comment by KingOlami** [comment]
Thank you @ashishnitinpatil
